//  MACROS  //

#undef TALOS_XX_FIELDS_HEADER
#undef TALOS_XX_FIELDS_DEFINE
#undef TALOS_XX_FIELDS_DESCRIBE
#undef TALOS_XX_FIELDS_TYPEDEF
#undef TALOS_XX_FIELDS_FOOTER
#undef TALOS_XX_STATICS_HEADER
#undef TALOS_XX_STATICS_DEFINE
#undef TALOS_XX_STATICS_DESCRIBE
#undef TALOS_XX_STATICS_TYPEDEF
#undef TALOS_XX_STATICS_FOOTER
