name: Build Talos
on: [workflow_dispatch, workflow_call]

jobs:
    target-build:
        runs-on: ${{ matrix.host }}
        name: Target '${{ matrix.label }}-${{ matrix.arch }}'

        strategy:
            fail-fast: true
            matrix:
                include:
                    - { label: darwin, arch: x64, host: macos-15-intel }
                    - { label: darwin, arch: arm64, host: macos-latest }
                    - { label: linux, arch: x64, host: ubuntu-latest }
                    - { label: linux, arch: arm64, host: ubuntu-24.04-arm }
                    - { label: windows, arch: x64, host: windows-latest }
                    # excluding windows-arm for now until ready for development
                    # - { label: windows, arch: arm64, host: windows-11-arm }

        steps:
            - uses: actions/checkout@v4
            - uses: lukka/get-cmake@latest

            - uses: ZhongRuoyu/setup-llvm@v0
              with:
                  llvm-version: ${{ runner.os == 'Windows' && 21 || 20 }}

            - uses: mozilla-actions/sccache-action@v0.0.9
              env: { SCCACHE_GHA_ENABLED: true }

            - name: Building '${{ matrix.label }}-${{ matrix.arch }}'
              run: ${{ github.workspace }}/scripts/compile/target.${{ runner.os == 'Windows' && 'ps1' || 'sh' }} ${{ matrix.label }} ${{ matrix.arch }} build

            - name: Testing '${{ matrix.label }}-${{ matrix.arch }}'
              timeout-minutes: 1 # should never go longer than this
              continue-on-error: true # sometimes first execution fails
              run: |
                  ${{ github.workspace }}/dist/bin/talos --version
                  ${{ github.workspace }}/dist/bin/talos task tools:test

            - name: Compress Artifacts
              uses: thedoctor0/zip-release@0.7.5
              with:
                  type: zip
                  directory: dist
                  filename: talos-${{ matrix.label }}-${{ matrix.arch }}.zip

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  overwrite: true
                  name: talos-${{ matrix.label }}-${{ matrix.arch }}
                  path: talos-${{ matrix.label }}-${{ matrix.arch }}.zip
