name: Release Nightly
description: Workflow for publishing Talos nightly releases
on: [workflow_dispatch]

jobs:
    nightly-staging:
        name: Stage Nightly Branch
        with: { release: nightly }
        uses: ./.github/workflows/staging.yml

    nightly-release:
        needs: [nightly-staging]
        with: { release: nightly, suffix: -nightly }
        uses: rroessler/langs.talos/.github/workflows/release.yml@nightly
