name: Release Worker
description: Workflow for publishing a Talos release

on:
    workflow_call:
        inputs:
            suffix:
                type: string
                default: ''
                required: false
                description: Version Suffix
            release:
                type: string
                required: true
                description: Release Type

jobs:
    release-build:
        name: Build Release
        uses: ./.github/workflows/builder.yml

    release-vscode:
        name: Publish VSCE
        needs: [release-build]
        if: inputs.release == 'stable'
        uses: ./.github/workflows/vscode.yml

    release-website:
        name: Publish Website
        needs: [release-build]
        if: inputs.release == 'stable'
        uses: ./.github/workflows/website.yml

    release-publish:
        name: Publish Release
        needs: [release-build]
        uses: ./.github/workflows/publish.yml
        with:
            suffix: ${{ inputs.suffix }}
            release: ${{ inputs.release }}
