name: Release Stable
description: Workflow for publishing Talos stable releases
on: [workflow_dispatch]

jobs:
    stable-release:
        name: Stable Dispatch
        with: { release: stable }
        uses: ./.github/workflows/release.yml
