name: Stage Release
description: Workflow for staging Talos release branches

on:
    workflow_call:
        inputs:
            release:
                type: string
                required: true
                description: Release Type

jobs:
    staging-branch:
        name: Staging '${{ inputs.release }}' Branch
        runs-on: ubuntu-latest
        permissions: { contents: write }
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  ref: ${{ inputs.release }}

            - name: Configure User
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Merge Branch '${{ inputs.release }}'
              run: |
                  git merge origin/main -X theirs --allow-unrelated-histories -m "Automated merge of '${{ inputs.release }}'"

            - uses: oven-sh/setup-bun@v2
            - name: Update Versioning
              run: |
                  bun install
                  bun tools:version

            - name: Commit Changes
              uses: stefanzweifel/git-auto-commit-action@v7
              with:
                  branch: ${{ inputs.release }}
                  commit_message: Automated versioning of '${{ inputs.release }}'
